### ISSUE TITLE
Declaring multiple vars in for-loop causes a crash

### ISSUE THREAD

**Issue by nene** [mohebifar/lebab#111]
For example the following code:

```js
for (var i = 0, len = arr.length; i < len; i++) {
}
```

results in the following:

```
/Users/nene/work/lebab/lib/utils/multi-replace-statement.js:24
  var index = parentNode.body.indexOf(node);
                              ^

TypeError: parentNode.body.indexOf is not a function
    at multiReplaceStatement (/Users/nene/work/lebab/lib/utils/multi-replace-statement.js:24:31)
    at /Users/nene/work/lebab/lib/transform/let.js:169:51
    at Array.forEach (native)
    at transformVarsToLetOrConst (/Users/nene/work/lebab/lib/transform/let.js:154:31)
    at leaveFunction (/Users/nene/work/lebab/lib/transform/let.js:148:3)
    at leaveProgram (/Users/nene/work/lebab/lib/transform/let.js:143:3)
    at Controller.leave (/Users/nene/work/lebab/lib/transform/let.js:83:9)
    at Controller.__execute (/Users/nene/work/lebab/node_modules/estraverse/estraverse.js:397:31)
    at Controller.traverse (/Users/nene/work/lebab/node_modules/estraverse/estraverse.js:491:28)
    at Object.traverse (/Users/nene/work/lebab/node_modules/estraverse/estraverse.js:713:27)
```

The problem is that variable `i` is incremented with `i++` so we want to transform it to `let`. But variable `len` is never modified, so we want to transform it to `const`. In such case our normal course of action is to break a single VariableDeclaration into multiple ones, which Lebab is attempting to do, but there can only be one VariableDeclaration within for-loop initializer, so we end up crashing.

**Comment by nene** [comment]
The same problem happens with VariableDeclarations inside switch cases:

```js
switch (nr) {
    case 1:
        var x = 1, y = 2;
        x++;
}
```

Here the problem is, that SwitchCase node does not have a `body`, instead it has `consequent`.
