### ISSUE TITLE
Exception occurs with some code

### ISSUE THREAD

**Issue by lukeapage** [mohebifar/lebab#153]
```
C:\npmprefix\node_modules\lebab\lib\scope\function-hoister.js:106
            _this2.functionScope.register(node.id.name, new _scopeVariable2['default'](node));
                                                 ^

TypeError: Cannot read property 'name' of null
    at Controller.enter (C:\npmprefix\node_modules\lebab\lib\scope\function-hoister.js:106:50)
    at Controller.__execute (C:\npmprefix\node_modules\lebab\node_modules\estraverse\estraverse.js:397:31)
    at Controller.traverse (C:\npmprefix\node_modules\lebab\node_modules\estraverse\estraverse.js:501:28)
    at Object.traverse (C:\npmprefix\node_modules\lebab\node_modules\estraverse\estraverse.js:713:27)
    at Object.traverse (C:\npmprefix\node_modules\lebab\lib\traverser.js:42:36)
    at FunctionHoister.hoistVariables (C:\npmprefix\node_modules\lebab\lib\scope\function-hoister.js:100:30)
    at FunctionHoister.hoist (C:\npmprefix\node_modules\lebab\lib\scope\function-hoister.js:79:12)
    at hoistFunction (C:\npmprefix\node_modules\lebab\lib\transform\let.js:144:53)
    at enterProgram (C:\npmprefix\node_modules\lebab\lib\transform\let.js:117:3)
    at Controller.enter (C:\npmprefix\node_modules\lebab\lib\transform\let.js:60:9)
```

**Comment by nene** [comment]
Could you please include the code that causes Lebab to throw this exception so we could reproduce it.

**Comment by lukeapage** [comment]
Its a bit difficult because I'm running it on 100's of files. I've printed out the code it fails on in function-hoister

```
Node {
  type: 'FunctionDeclaration',
  start: 63,
  end: 373,
  loc: null,
  id: null,
  generator: false,
  expression: false,
  params: [],
  body:
   Node {
     type: 'BlockStatement',
     start: 74,
     end: 373,
     loc: SourceLocation { start: [Object], end: [Object], lines: Lines {}, indent: 0 },
     body: [ [Object] ] } }
```

I assume that an anonymous function that gets into this code will fail? I added a guard around this particular line that failed in function hoister ..

```
          } else if (functionType.isFunctionDeclaration(node)) {
            if (!node.id) {
               console.log(node);
            } else {
                _this2.functionScope.register(node.id.name, new _scopeVariable2['default'](node));¬
            }
            // Skip anything inside the nested function
            return _traverser2['default'].VisitorOption.Skip;
```

hopefully thats enough to figure out the issue?

**Comment by nene** [comment]
It's probably also in your own interest to find out the problematic file.
It's likely quicker to adjust the file a bit on your side than to wait for
me to implement and release a fix.

**Comment by lukeapage** [comment]
I patched it locally, so I don't need a fix, but here is a repro

```
export default function() {
    var a;
}
```

**Comment by nene** [comment]
Ah... thanks. Now I get it.

- In ES5 one could only have a an anonymous FunctionExpression, but FunctionDeclarations always needed a name.
- In ES6 however the FunctionDeclarations in default export don't need a name. But Lebab assumes they always must have a name.

Should be pretty easy to fix.
