### ISSUE TITLE
Make unit tests work in windows

### ISSUE THREAD

**Issue by nene** [mohebifar/lebab#180]
Something to do with glob pattern.

See comments in pull request: 178

**Comment by oliversalzburg** [comment]
npm will run `scripts` through the default shell on the OS. On Windows, this is `cmd.exe`, which differs in many ways from POSIX-compliant shells like bash.

One way to work around this issue is to strictly depend on a certain shell and invoke it in the npm script:
```
"test": "bash -c \"npm run prepublish && mocha --compilers js:babel-register 'test/**/*Test.js'\""
```

This will work on all operating systems, as long as `bash` is available.

That being said, the core issue here is the use of single-quotes, which is not acceptable for the Windows command line processor, which only respects double-quotes. So one solution would be:
```
"test": "npm run prepublish && mocha --compilers js:babel-register \"test/**/*Test.js\""
```

This will make the tests *run*, but they won't pass due to other Windows-related issues:
```shell
  1) Smoke test for the executable script when no input/output files given reads STDIN and writes STDOUT:
     Uncaught expected [Error: Command failed: node ./bin/index.js -t let,arrow < test/test-data.js > test/output.js
fs.js:640
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open 'D:\dev\stdin'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.read (D:\lebab\lib\io.js:30:27)
    at Cli.transformFile (D:\lebab\lib\Cli.js:72:64)
    at Cli.run (D:\lebab\lib\Cli.js:66:14)
    at Object.<anonymous> (D:\lebab\bin\index.js:4:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
] to equal null
  AssertionError: expected [Error: Command failed: node ./bin/index.js -t let,arrow < test/test-data.js > test/output.js
  fs.js:640
    return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                   ^

  Error: ENOENT: no such file or directory, open 'D:\dev\stdin'
      at Error (native)
      at Object.fs.openSync (fs.js:640:18)
      at Object.fs.readFileSync (fs.js:508:33)
      at Object.read (D:\lebab\lib\io.js:30:27)
      at Cli.transformFile (D:\lebab\lib\Cli.js:72:64)
      at Cli.run (D:\lebab\lib\Cli.js:66:14)
      at Object.<anonymous> (D:\lebab\bin\index.js:4:23)
  ] to equal null
      at D:/lebab/test/binTest.js:40:26
      at ChildProcess.exithandler (child_process.js:213:5)
      at maybeClose (internal/child_process.js:852:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

  2) Command Line Interface when --replace used with existing dir name, turns it into glob pattern:

      AssertionError: expected 'lib\\**\\*.js' to equal 'lib/**/*.js'
      + expected - actual

      -lib\**\*.js
      +lib/**/*.js

      at Context.<anonymous> (D:/lebab/test/parseOptionsTest.js:102:32)
      at callFn (D:\lebab\node_modules\mocha\lib\runnable.js:326:21)
      at Test.Runnable.run (D:\lebab\node_modules\mocha\lib\runnable.js:319:7)
      at Runner.runTest (D:\lebab\node_modules\mocha\lib\runner.js:422:10)
      at D:\lebab\node_modules\mocha\lib\runner.js:528:12
      at next (D:\lebab\node_modules\mocha\lib\runner.js:342:14)
      at D:\lebab\node_modules\mocha\lib\runner.js:352:7
      at next (D:\lebab\node_modules\mocha\lib\runner.js:284:14)
      at D:\lebab\node_modules\mocha\lib\runner.js:315:7
      at done (D:\lebab\node_modules\mocha\lib\runnable.js:287:5)
      at callFn (D:\lebab\node_modules\mocha\lib\runnable.js:344:7)
      at Hook.Runnable.run (D:\lebab\node_modules\mocha\lib\runnable.js:319:7)
      at next (D:\lebab\node_modules\mocha\lib\runner.js:298:10)
      at Immediate.<anonymous> (D:\lebab\node_modules\mocha\lib\runner.js:320:5)
```

**Comment by nene** [comment]
Changed the quotes and did some other changes that should make the Windows test work. As the STDIN reading doesn't work in Windows, I'm skipping this test.

@oliversalzburg perhaps you could test if you can run the tests now in Windows.

**Comment by oliversalzburg** [comment]
```
  332 passing (4s)
  1 pending
```
Looks good :)

**Comment by nene** [comment]
Great!
