### ISSUE TITLE
Crash inside transformation/default-arguments, cannot read map of undefined

### ISSUE THREAD

**Issue by scottopell** [mohebifar/lebab#42]
Trying to use your tool on this code from Mike Chambers

https://github.com/mikechambers/ExamplesByMesh/blob/master/JavaScript/QuadTree/src/QuadTree.js

and got the following message.

```
→ xto6 QuadTree.js -o qqq.js
/usr/local/lib/node_modules/xto6/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^
TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/xto6/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/xto6/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/xto6/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/xto6/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/xto6/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/xto6/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/xto6/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/xto6/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/xto6/bin/index.js:37:3)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (module.js:355:32)
  at Function.Module._load (module.js:310:12)
  at Function.Module.runMain (module.js:501:10)
  at startup (node.js:129:16)
  at node.js:814:3
```

Any ideas where to start debugging this?

**Comment by gunta** [comment]
+1

**Comment by nene** [comment]
Although it looks from the stack trace that it's related to default-arguments, the underlying bug is actually that the classes transform is unable to handle the following:

```js
function Foo() {
}
Foo.prototype.bar = 123;
```

Lebab thinks that anything assigned to `Foo.prototype` must be a function and tries to extract the arguments and body, but there is none, and so it crashes.
