### ISSUE TITLE
Handle files with `#!/usr/bin/env node`

### ISSUE THREAD

**Issue by vnykmshr** [mohebifar/lebab#55]
Throws error when processing a file containing `#!/usr/bin/env node`

```
/usr/local/lib/node_modules/xto6/node_modules/esprima-fb/esprima.js:7736
            throw e;
            ^

Error: Line 1: Unexpected token ILLEGAL
  at throwError (/usr/local/lib/node_modules/xto6/node_modules/esprima-fb/esprima.js:2824:21)
  at scanPunctuator (/usr/local/lib/node_modules/xto6/node_modules/esprima-fb/esprima.js:1011:9)
  at advance (/usr/local/lib/node_modules/xto6/node_modules/esprima-fb/esprima.js:1747:16)
  at peek (/usr/local/lib/node_modules/xto6/node_modules/esprima-fb/esprima.js:1773:21)
  at parseProgram (/usr/local/lib/node_modules/xto6/node_modules/esprima-fb/esprima.js:6546:9)
  at Object.parse (/usr/local/lib/node_modules/xto6/node_modules/esprima-fb/esprima.js:7724:23)
  at Object.parse (/usr/local/lib/node_modules/xto6/node_modules/recast/lib/parser.js:26:34)
  at Object.read (/usr/local/lib/node_modules/xto6/lib/utils/ast-generator.js:66:33)
  at Object.readFile (/usr/local/lib/node_modules/xto6/lib/utils/ast-generator.js:42:17)
  at Transformer.readFile (/usr/local/lib/node_modules/xto6/lib/transformer.js:113:51)
  at module.exports (/usr/local/lib/node_modules/xto6/bin/file.js:13:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/xto6/bin/index.js:37:3)
  at Module._compile (module.js:425:26)
  at Object.Module._extensions..js (module.js:432:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:313:12)
  at Function.Module.runMain (module.js:457:10)
  at startup (node.js:138:18)
  at node.js:974:3
```

**Comment by simoneduca** [comment]
I've just installed Lebab but I'm getting the same issue. I've got the Recast 3.5.3 installed so don't know what's causing this. Thoughts?

**Comment by nene** [comment]
Can you post the specific code that's causing the problem (preferably reduced down to the minimum amount of lines that still cause it).

We have a unit-test checking that `#!` comments get ignored, and I also just confirmed it manually. But perhaps you're using some variation of the syntax that we fail to detect.

**Comment by simoneduca** [comment]
Hi @nene, after global install I did:

`lebab src/index.js -o src/index.js --enable arrow`
 
and this was the output

```
/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:5701
            throw e;
            ^
Error: Line 24: Unexpected token <
    at constructError (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:2406:21)
    at createError (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:2425:17)
    at unexpectedTokenError (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:2499:13)
    at throwUnexpectedToken (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:2504:15)
    at parsePrimaryExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:3306:13)
    at inheritCoverGrammar (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:2680:18)
    at parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:3413:20)
    at inheritCoverGrammar (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:2680:18)
    at parsePostfixExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:3489:16)
    at parseUnaryExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima/esprima.js:3549:20)
```

This is the file I'm trying to process:

```
import React from 'react';
import ReactDOM from 'react-dom';
import { Router, Route } from 'react-router';
import { Provider } from 'react-redux';
import App from './components/App';
import PoweredBy from './components/Powered-by';
import About from './components/About';

import { oauth } from 'panoptes-client';
import { config } from './constants/config';

import configureStore from './store';
const store = configureStore();

// Todo: let's find a better way to include Styles,
// currently Styles looks like an unused var to eslint
import Styles from './styles/main.styl';

window.React = React;

oauth.init(config.panoptesAppId)
  .then(function () {
    ReactDOM.render(
      <Provider store={store}>
        <Router>
          <Route path="/" component={App}>
            <Route path="/about" component={About}/>
            <Route path="/poweredby" component={PoweredBy}/>
          </Route>
        </Router>
      </Provider>
      , document.getElementById('root')
    );
});
```

**Comment by nene** [comment]
Well... This code has no hash-bang comment in it, so it's completely
unrelated to the originaal issue.

Instead I see JSX syntax. That's currently not supported by lebab (as it's
unsupported by underlying Esprima parser).

**Comment by simoneduca** [comment]
Oh dear, thanks and sorry for the confusion!
