### ISSUE TITLE
Large amount of errors

### ISSUE THREAD

**Issue by dbkaplun** [mohebifar/lebab#62]
Here are the results of running `lebab` on every .js file in [slap-editor/slap@`c2d05cd`](https://github.com/slap-editor/slap/tree/c2d05cd). The affected files are listed *after* the tracebacks.
```
$ find . -type f -not -path '*/node_modules/*' -iname '*.js' -exec sh -c 'lebab {} -o {} || echo {}' \;
/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:7736
            throw e;
            ^

Error: Line 1: Unexpected token (
  at throwError (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:2819:21)
  at throwUnexpected (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:2881:9)
  at consumeSemicolon (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:3004:13)
  at parseExpressionStatement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:5173:9)
  at parseStatement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:5665:24)
  at parseSourceElement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6486:20)
  at parseFunctionSourceElements (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:5791:29)
  at parseFunctionDeclaration (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:5991:16)
  at parseSourceElement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6441:24)
  at parseFunctionSourceElements (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:5791:29)
  at parseConciseBody (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:5738:20)
  at parseArrowFunctionExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4117:16)
  at parseAssignmentExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4178:24)
  at parseExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4250:16)
  at parseExpressionStatement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:5172:45)
  at parseStatement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:5665:24)
  at parseSourceElement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6486:20)
  at parseProgramElement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6502:16)
  at parseProgramElements (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6534:29)
  at parseProgram (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6547:16)
  at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:7724:23)
  at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/recast/lib/parser.js:26:34)
  at Object.read (/usr/local/lib/node_modules/lebab/lib/utils/ast-generator.js:66:33)
  at Object.readFile (/usr/local/lib/node_modules/lebab/lib/utils/ast-generator.js:42:17)
  at Transformer.readFile (/usr/local/lib/node_modules/lebab/lib/transformer.js:113:51)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:13:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./coverage/lcov-report/prettify.js
/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:7736
            throw e;
            ^

Error: Line 3: Const must be initialized
  at throwError (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:2824:21)
  at parseVariableDeclaration (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4839:17)
  at parseVariableDeclarationList (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4855:23)
  at parseConstLetDeclaration (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4886:24)
  at parseSourceElement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6439:24)
  at parseFunctionSourceElements (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:5791:29)
  at parseConciseBody (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:5738:20)
  at parseArrowFunctionExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4117:16)
  at parseAssignmentExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4178:24)
  at parseExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4250:16)
  at parseGroupExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:3482:16)
  at parsePrimaryExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:3575:20)
  at parseLeftHandSideExpressionAllowCall (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:3683:61)
  at parsePostfixExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:3723:20)
  at parseUnaryExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:3790:16)
  at parseBinaryExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:3880:16)
  at parseConditionalExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:3940:16)
  at parseAssignmentExpression (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4193:16)
  at parseVariableDeclaration (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4842:20)
  at parseVariableDeclarationList (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4855:23)
  at parseConstLetDeclaration (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:4886:24)
  at parseSourceElement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6439:24)
  at parseProgramElement (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6502:16)
  at parseProgramElements (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6534:29)
  at parseProgram (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6547:16)
  at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:7724:23)
  at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/recast/lib/parser.js:26:34)
  at Object.read (/usr/local/lib/node_modules/lebab/lib/utils/ast-generator.js:66:33)
  at Object.readFile (/usr/local/lib/node_modules/lebab/lib/utils/ast-generator.js:42:17)
  at Transformer.readFile (/usr/local/lib/node_modules/lebab/lib/transformer.js:113:51)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:13:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./coverage/lcov-report/sorter.js
/usr/local/lib/node_modules/lebab/lib/transformation/object-methods.js:25
      if (property.value.type === 'FunctionExpression') {
                        ^

TypeError: Cannot read property 'type' of undefined
  at Controller.functionToMethod (/usr/local/lib/node_modules/lebab/lib/transformation/object-methods.js:25:25)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/object-methods.js:14:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/cli.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/BaseFindForm.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/BaseForm.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/Button.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/FileBrowser.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/FindForm.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/GoLineForm.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/Header.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/Pane.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/SaveAsCloseForm.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/SaveAsForm.js
/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29
    lastFunction._args = node.params.map(function (arg) {
                                    ^

TypeError: Cannot read property 'map' of undefined
  at Controller.findDefaultAssignments (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:29:37)
  at Controller.__execute (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:399:31)
  at Controller.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:633:27)
  at Object.replace (/usr/local/lib/node_modules/lebab/node_modules/estraverse/estraverse.js:714:27)
  at exports.default (/usr/local/lib/node_modules/lebab/lib/transformation/default-arguments.js:16:27)
  at Transformer.applyTransformation (/usr/local/lib/node_modules/lebab/lib/transformer.js:140:7)
  at Transformer.applyTransformations (/usr/local/lib/node_modules/lebab/lib/transformer.js:152:14)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:14:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./lib/ui/Slap.js
/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:7736
            throw e;
            ^

Error: Line 1: Unexpected token ILLEGAL
  at throwError (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:2824:21)
  at scanPunctuator (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:1011:9)
  at advance (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:1747:16)
  at peek (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:1773:21)
  at parseProgram (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6546:9)
  at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:7724:23)
  at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/recast/lib/parser.js:26:34)
  at Object.read (/usr/local/lib/node_modules/lebab/lib/utils/ast-generator.js:66:33)
  at Object.readFile (/usr/local/lib/node_modules/lebab/lib/utils/ast-generator.js:42:17)
  at Transformer.readFile (/usr/local/lib/node_modules/lebab/lib/transformer.js:113:51)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:13:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./slap.js
/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:7736
            throw e;
            ^

Error: Line 1: Unexpected token ILLEGAL
  at throwError (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:2824:21)
  at scanPunctuator (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:1011:9)
  at advance (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:1747:16)
  at peek (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:1773:21)
  at parseProgram (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6546:9)
  at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:7724:23)
  at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/recast/lib/parser.js:26:34)
  at Object.read (/usr/local/lib/node_modules/lebab/lib/utils/ast-generator.js:66:33)
  at Object.readFile (/usr/local/lib/node_modules/lebab/lib/utils/ast-generator.js:42:17)
  at Transformer.readFile (/usr/local/lib/node_modules/lebab/lib/transformer.js:113:51)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:13:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./spec/cli.js
/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:7736
            throw e;
            ^

Error: Line 1: Unexpected token ILLEGAL
  at throwError (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:2824:21)
  at scanPunctuator (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:1011:9)
  at advance (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:1747:16)
  at peek (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:1773:21)
  at parseProgram (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:6546:9)
  at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/recast/node_modules/esprima-fb/esprima.js:7724:23)
  at Object.parse (/usr/local/lib/node_modules/lebab/node_modules/recast/lib/parser.js:26:34)
  at Object.read (/usr/local/lib/node_modules/lebab/lib/utils/ast-generator.js:66:33)
  at Object.readFile (/usr/local/lib/node_modules/lebab/lib/utils/ast-generator.js:42:17)
  at Transformer.readFile (/usr/local/lib/node_modules/lebab/lib/transformer.js:113:51)
  at module.exports (/usr/local/lib/node_modules/lebab/bin/file.js:13:15)
  at Object.<anonymous> (/usr/local/lib/node_modules/lebab/bin/index.js:37:3)
  at Module._compile (module.js:435:26)
  at Object.Module._extensions..js (module.js:442:10)
  at Module.load (module.js:356:32)
  at Function.Module._load (module.js:311:12)
  at Function.Module.runMain (module.js:467:10)
  at startup (node.js:134:18)
  at node.js:961:3

./spec/index.js
```

**Comment by dbkaplun** [comment]
Any progress on this? This is (or should be) a blocker, as valid JS is causing lebab to throw an exception.

**Comment by mohebifar** [comment]
@dbkaplun We don't think that the existing code is extendable anymore. So, we are going to work on another alpha very soon.

**Comment by nene** [comment]
Several of these issues are parse errors coming from [Recast](https://github.com/benjamn/recast) that uses [esprima-fb](https://github.com/facebookarchive/esprima), the latter is however no more maintained and has fallen behind the main [Esprima](https://github.com/jquery/esprima) parser.

There's an issue in Recast to [move from `esprima-fb` to some other parser](https://github.com/benjamn/recast/issues/178). That issue is almost a year old though and no progress seems to be happening.

**Comment by nene** [comment]
Most of these old errors have been fixed with upgrade of `Recast` dependency.

Re-ran Lebab on https://github.com/slap-editor/slap codebase and discovered the following issues:

- `slap.js` fails because of `#!/usr/bin/env node` - issue #55
- `lib/cli.js` fails because reserved name `package` is used as a variable name, which Esprima doesn't like.
- all other files fail because of assignment to `SomeClass.prototype.__proto__` - the classes transform fails whenever something else than a function is assigned to prototype.
